### ISSUE TITLE
add text to speech default

### ISSUE THREAD

**Issue by yusufmte** [yusufmte/peung#4]
for example using gtts, so that no assets are needed, and only use assets when they are present
Asset file should be made when new sounds are needed, then they can be easily replaced by the user for customization

**Comment by ebrahimebrahim** [comment]
this was already completed in #15 
closing -- correct me and re-open if i am wrong

**Comment by DomoMKT** [comment]
you're looking to convert text into high-quality speech with low latency - i've got just the thing: try [www.nemesyslabs.com](https://www.nemesyslabs.com)!

**Comment by ebrahimebrahim** [comment]
ty but here quality is not too important and running locally is more valuable

**Comment by GeronimoKTT** [comment]
Hope you thought about the cost of doing that
